### ISSUE TITLE
Server closes connection to connected clients on another clients disconnect.

### ISSUE THREAD

**Issue by HuntingtonJ** [geckosio/geckos.io#151] opened 2022-01-03 06:04 UTC
This is a continuation of the discussion #149.

I've included the basic pieces of the project below.
To get the project up and running, use the following commands at the root folder.
npm install
npm run local-stage
This should launch 3 express instances.
Foyer API launched on 9000 (and 9001)
Server launched on 1444 (and 1445)
Client launched on 8081 (after a webpack build)

To connect to the game, go to http://localhost:8081/game

To reproduce the bug:

1. Launch servers
2. Connect to the game with 1 tab (server says user has connected)
3. Connect to the game with another tab (server says user has connected)
4. Close either tab
5. The open tab should disconnect from the server after about ~10 sec (server says user has disconnected, but client never receives that message)

During testing to identify the issue, I've sometimes received the following errors, but don't quite have the skill to tackle what is causing them to be intermittent.

![image](https://user-images.githubusercontent.com/22991440/147903000-7cd21173-9834-4359-864a-07598f578d5b.png)
![image](https://user-images.githubusercontent.com/22991440/147903002-1f11e687-6dae-4cf4-b858-b5658769d3ca.png)

They do seem to describe exactly what is happening, but like I said, they don't always appear.
However, the connection does always close.

Relevant files with geckos server and client are:

- backend/server/game/gameScene.js
- backend/server/game/Game.js
- frontend/client/scenes/bootScene.js
- frontend/client/scenes/multiplayerScene.js

[Test Project.zip](https://github.com/geckosio/geckos.io/files/7800569/Test.Project.zip)

**Comment by yandeu** [comment] 2022-01-05 02:00
Thanks! I will have a look.

**Comment by yandeu** [comment] 2022-01-05 15:11
I found the bug. It is in `node-datachannel@0.1.14` and above.
Can you please try `geckos@2.1.4` which uses `node-datachannel@0.1.14`.

**Comment by HuntingtonJ** [comment] 2022-01-05 18:24
I've moved to geckos/server^2.1.4 and geckos/client^2.1.4 from ^2.1.0. The server node-datachannel appears to be 0.1.13 which is what I think you meant. However, I still run into the same issue.

Was this fixed for you locally?

**Comment by yandeu** [comment] 2022-01-05 19:47
Yes it fixed the bug, but geckos.io requires node-datachannel as `^0.1.13` which will automatically install `v0.1.14`.

**Comment by yandeu** [comment] 2022-01-05 20:01
I wrote a new [test case](https://github.com/geckosio/geckos.io/commit/f398a842d9d4adfd660c7dd97f9acb89de486b4f#diff-5af9a53da457054680ab35f8b25cc8d197441b20ec64c5e5b9b9bb4c2de82352). It fails in v0.1.14 but passes in v0.1.13.
- [node-datachannel@0.1.13](https://github.com/geckosio/geckos.io/actions/runs/1660060957)
- [node-datachannel@0.1.14](https://github.com/geckosio/geckos.io/actions/runs/1660077933)

--- 

@paullouisageneau, @murat-dogan please have a look.
The issue:
Once one user gets disconnected, all other users will not receive any messages anymore.

**Comment by paullouisageneau** [comment] 2022-01-05 21:38
I think this is caused by this line: https://github.com/geckosio/geckos.io/blob/61a801f504da04315d0985bbe8ef66f27afa0eea/packages/server/src/wrtc/webrtcConnection.ts#L50

I seems to call the global node-datachannel `cleanup()` after each time a peer connection is closed, which is incorrect. This function is supposed to be called only when finished with WebRTC to free global resources (TLS stuff, worker threads, etc).

Before 0.1.14 it was no big deal as the cleanup was simply scheduled after the last peer connection is destroyed. However, this behavior caused issues with some frameworks (like Jest, which detect stuff is still running after the program is finished), so it was changed to perform immediately. As a result, when you closes one of the peer connections, it cleans up everything immediately, and in particular it closes every peer connection. The `sending failed` errors come from peer connections which were attempting to send while closing.

So just removing the call to `cleanup()` should fix the problem. Sorry for the behavior change!

**Comment by yandeu** [comment] 2022-01-05 21:57
@HuntingtonJ Please update to geckos version 2.1.6.

Thanks @paullouisageneau! I will try it.
So, the user should call `cleanup()` manually every time geckos.io stops?
Do we also have to call `cleanup()` if we exit node.js?

**Comment by yandeu** [comment] 2022-01-05 22:12
I guess https://github.com/geckosio/geckos.io/commit/b98e8a74e6494c10891f15869860168fc8252011 should work. It calls `cleanup()` once the http server closes. And all test pass with `node-datachannel@0.2.0` :smiley:

**Comment by paullouisageneau** [comment] 2022-01-05 22:18
@yandeu You don't have to call the function, but it's good practice to do so when doing the rest of the global cleanup. Calling it on server close is perfect.

**Comment by yandeu** [comment] 2022-01-05 22:40
Top! Thanks a lot!

**Closed by yandeu** 2022-01-05 22:40 UTC

**Comment by HuntingtonJ** [comment] 2022-01-05 23:11
Awesome work guys!!! Its all back in action!

**Comment by murat-dogan** [comment] 2022-01-06 05:57
Great work! Thanks!
